"""Remove all GitHub references from source files.

The user wants to be reached only via email. We strip:
- Footer GitHub links (anchor + parent <li>)
- "Open source on GitHub" claims
- "File a GitHub issue" instructions
- Author profile links
- Standalone GitHub repo references

Replaces with email-based contact where context calls for it. Built/dist
files are regenerated by Hugo and Astro after source changes — we only
touch the techtools365-landing public/*.html (which IS the source for
that static site) plus Hugo `content/*.md` plus Astro `src/**/*.astro`.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(r"C:\Prasad\Projects\claude_workspace\BlackHole\data-products")

# Source files only — built artifacts will regenerate
SOURCES = [
    # techtools365-landing static HTML (these ARE the source)
    "techtools365-landing/public/index.html",
    "techtools365-landing/public/about/index.html",
    "techtools365-landing/public/contact/index.html",
    "techtools365-landing/public/privacy/index.html",
    "techtools365-landing/public/blog/index.html",
    "techtools365-landing/public/blog/techtools365-methodology/index.html",
    "techtools365-landing/public/blog/how-to-choose-a-vpn-2026/index.html",
    "techtools365-landing/public/blog/visa-stacking-explained-2026/index.html",
    "techtools365-landing/public/blog/uae-vs-india-take-home-salary-2026/index.html",
    # Hugo source
    "toolversus/content/about.md",
    "toolversus/content/contact.md",
    "toolversus/layouts/_default/baseof.html",
    # Astro source
    "visapathway/src/layouts/BaseLayout.astro",
    "visapathway/src/pages/methodology.astro",
    "calcstack/src/layouts/BaseLayout.astro",
]

# (pattern, replacement, is_regex) — applied in order. Regex uses re.DOTALL.
RULES = [
    # 1. Remove footer <li><a ...>GitHub repo ↗</a></li> patterns (with various whitespace/quotes)
    (r'\s*<li>\s*<a href="https://github\.com/dppalukuri/BlackHole"[^>]*>GitHub repo[^<]*</a>\s*</li>', "", True),
    (r'\s*<li>\s*<a href="https://github\.com/dppalukuri/BlackHole"[^>]*>GitHub[^<]*</a>\s*</li>', "", True),
    # 2. Remove standalone <a>GitHub ↗</a> anchors in nav lists / inline (no <li> wrapper)
    (r'\s*<a href="https://github\.com/dppalukuri/BlackHole"[^>]*>GitHub\s*\u2197?\s*</a>', "", True),
    # 3. Inline <a>GitHub</a> mentions in prose — replace with "the site is open to corrections via email"
    (r'<a href="https://github\.com/dppalukuri/BlackHole"[^>]*>GitHub</a>', '<a href="/contact/">email</a>', True),
    (r'<a href="https://github\.com/dppalukuri/BlackHole"[^>]*>BlackHole</a>', '<a href="/contact/">email</a>', True),
    (r'<a href="https://github\.com/dppalukuri/BlackHole/[^"]+"[^>]*>([^<]+)</a>', r'\1', True),  # nested links: text only
    (r'<a href="https://github\.com/dppalukuri"[^>]*>([^<]+)</a>', r'\1', True),  # profile links: text only
    # 4. Replace specific phrases (case sensitive)
    (r"file a GitHub issue or\s*", "", True),
    (r"file a GitHub issue", "email us", False),
    (r"the GitHub repo", "us", False),
    (r"BlackHole repo", "site", False),
    (r"follow the\s*<a href=\"/contact/\">email</a>\s*\u2014", "email us \u2014", True),
    (r"\(<a href=\"/contact/\">email</a>\)", "", True),
    # 5. Markdown footer-link removal in toolversus content (just in case)
    (r'\* \[GitHub\]\(https://github\.com/dppalukuri/BlackHole\)\s*', "", True),
    # 6. Markdown link to repo in about.md / contact.md — replace with email
    (r'\[GitHub\]\(https://github\.com/dppalukuri/BlackHole\)', '[email](/contact/)', False),
    (r'\[Durga Prasad\]\(https://github\.com/dppalukuri\)', 'Durga Prasad', False),
    (r'\[github/BlackHole\]\(https://github\.com/dppalukuri/BlackHole\)', 'TechTools365', False),
    (r'\[GitHub repo\]\(https://github\.com/dppalukuri/BlackHole\)', '[email us](/contact/)', False),
    (r"\(https://github\.com/dppalukuri/BlackHole/tree/[^\)]+\)", "(/contact/)", True),
    (r"\(https://github\.com/dppalukuri/BlackHole/commits/main\)", "(/contact/)", True),
    (r"<a href=\"https://github\.com/dppalukuri/BlackHole\"[^>]*>github/BlackHole</a>", "TechTools365", True),
]

def normalize_whitespace(text: str) -> str:
    """Collapse runs of whitespace inside HTML attributes / between tags after deletion."""
    # Remove multi-blank lines
    text = re.sub(r'\n\s*\n\s*\n+', '\n\n', text)
    # Collapse double spaces inside lines
    return text

count_files = 0
total_changes = 0
for rel in SOURCES:
    p = ROOT / rel
    if not p.exists():
        print(f"  [skip] {rel}")
        continue
    text = p.read_text(encoding="utf-8")
    orig = text
    file_changes = 0
    for pat, repl, is_regex in RULES:
        if is_regex:
            new_text, n = re.subn(pat, repl, text, flags=re.DOTALL)
        else:
            n = text.count(pat)
            new_text = text.replace(pat, repl)
        if n:
            text = new_text
            file_changes += n
    text = normalize_whitespace(text)
    if text != orig:
        p.write_text(text, encoding="utf-8")
        count_files += 1
        total_changes += file_changes
        print(f"  [updated] {rel} (+{file_changes} replacements)")
    else:
        print(f"  [no change] {rel}")
print(f"\nFiles updated: {count_files}, total replacements: {total_changes}")
