"""Update name (Prasad → Durga Prasad) and email across the source files
(public HTML pages will be regenerated by Hugo / Astro builds for the
subsites, and the techtools365-landing pages are static HTML so we update
those in-place too)."""
from __future__ import annotations
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(r"C:\Prasad\Projects\claude_workspace\BlackHole\data-products")

OLD_EMAIL = "durga.prasad.22121993@gmail.com"
NEW_EMAIL = "palukuri.biz@gmail.com"

# Sources we rewrite (Hugo + Astro re-build their public/dist from these):
SOURCES = [
    "techtools365-landing/public/about/index.html",
    "techtools365-landing/public/contact/index.html",
    "techtools365-landing/public/blog/techtools365-methodology/index.html",
    "techtools365-landing/public/blog/index.html",
    "techtools365-landing/public/blog/how-to-choose-a-vpn-2026/index.html",
    "techtools365-landing/public/blog/visa-stacking-explained-2026/index.html",
    "techtools365-landing/public/blog/uae-vs-india-take-home-salary-2026/index.html",
    "techtools365-landing/public/index.html",
    "techtools365-landing/public/privacy/index.html",
    "toolversus/content/about.md",
    "toolversus/content/contact.md",
]

# Name-replacement rules — be specific so we don't change the GitHub handle "dppalukuri"
# or other unrelated occurrences. The `>Prasad<` pattern targets only the displayed name.
NAME_RULES = [
    (">Prasad</a>", ">Durga Prasad</a>"),       # GitHub anchor display text
    ("by Prasad", "by Durga Prasad"),           # Generic prose
    ("operated by Prasad", "operated by Durga Prasad"),
    ("Prasad in Dubai", "Durga Prasad in Dubai"),
    ("run by Prasad", "run by Durga Prasad"),
    ("\nPrasad — Indian", "\nDurga Prasad — Indian"),  # Specific phrase in About
    ("[Prasad]", "[Durga Prasad]"),             # Markdown link text in toolversus/content/about.md
]

total = 0
for rel in SOURCES:
    p = ROOT / rel
    if not p.exists():
        print(f"  [skip] {rel}")
        continue
    text = p.read_text(encoding="utf-8")
    orig = text
    text = text.replace(OLD_EMAIL, NEW_EMAIL)
    for old, new in NAME_RULES:
        text = text.replace(old, new)
    if text != orig:
        p.write_text(text, encoding="utf-8")
        total += 1
        print(f"  [updated] {rel}")
    else:
        print(f"  [no change] {rel}")
print(f"\nTotal files updated: {total}")
